### ISSUE TITLE
'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by MTekinAU** [invictus-ir/Microsoft-Extractor-Suite#104] opened 2024-11-14 04:09 UTC
Hi, 
I can view logs using Audit Portal in Microsoft Purview, however when I run Get-UALAll I get the following error:

"[ERROR] An error occurred: The term 'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Search-UnifiedAuditLog : The term 'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At C:\Users\-\Downloads\Microsoft-Extractor-Suite\Microsoft-Extractor-Suite-main\Scripts\Get-UAL.ps1:91 char:22
+         $areYouConnected = Search-UnifiedAuditLog -StartDate (Get-Dat ...
+                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Search-UnifiedAuditLog:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException"

I tried to install Microsoft-Extractor-Suite on different device + upgraded to PowerShell 7, but I am still having same problem. 

How can I fix it?  
Thank you.

**Comment by JoeyInvictus** [comment] 2024-11-14 07:34
Hi,

The Extractor Suite relies on the `Search-UnifiedAuditLog` cmdlet from the Exchange Online PowerShell module. This error indicates that the cmdlet cannot be found, which prevents the extractor from running properly. My guess would be that the module may not be installed, or the session is not connected or you don't have the right permissions. 

You need to install the `ExchangeOnlineManagement` module:
`Install-Module -Name ExchangeOnlineManagement`

Connect to Exchange Online (you will be prompted for credentials)
`Connect-ExchangeOnline`

Make sure the account you're using has the required permissions to access the `Search-UnifiedAuditLog` cmdlet. Specifically, this requires:

- Global Reader, Global Administrator, or Compliance Administrator roles (more admin roles will do the job we always ask for global reader).
- View-Only Audit Logs or Audit Logs roles must also be assigned to your account, this is often overlooked but is needed to run the `Search-UnifiedAuditLog` cmdlet.

You might find this snippet from our documentation helpful for setting up an account with the correct permissions: 
https://microsoft-365-extractor-suite.readthedocs.io/en/latest/installation/Prerequisites.html

During our investigations we often ask for a Global Reader account with Audit Log roles assigned, which can be accomplished via the following steps:

1. Create a new user account in the Microsoft 365 admin center (admin.microsoft.com)
2. Assign the new user ‘Global Reader’ role
3. Go to Roles and select ‘Exchange’ and create a new role group
4. Next, select the ‘Unified Audit’ role and go to ‘Permissions’ and select the ‘View-Only Audit Logs’ permission
5. Add the new user to this role group

**Comment by gja3** [comment] 2024-11-18 04:28
Hi Joey,

I'm running into the same issue and have in the past. Unfortunately, this has prevented me from using this tool thus far. 

I can confirm that I have installed ExchangeOnlineManagement using the given the command. I've connected to Exchange using `Connect-ExchangeOnline` and authenticating with MFA through the pop-up window, as an account with Global Reader. I've also tried using `Connect-M365` as well or instead in case that made any difference. Nevertheless, I run into the same issue. 

I am having this same issue across two different machines, a fresh install of Windows 10 (with requirements set up according to the M-E-S documentation) and a relatively fresh install of Windows 11. I come from the *nix world and am not well versed in PowerShell so perhaps it's just a simple path/dependency issue of some sort, but in any case this seems to be an issue by default. 

I appreciate your support and look forward to getting this thing working. 

[ERROR] An error occurred: The term 'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Search-UnifiedAuditLog : The term 'Search-UnifiedAuditLog' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by MTekinAU** [comment] 2024-11-18 04:43
Hi @gja3,

Ensure that you have the required permissions.
Then I would recommend trying the following:

1. Start administrator PowerShell
2. Download GitHub M-E-S source code and cd into the folder
3. Run ` Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser`
4. Run `Install-module -name ExchangeOnlineManagement` 
5. Run `Install-module -name Microsoft.Graph`
6.  Run `Install-module -name Az`
7. Run `Install-Module -Name AzureADPreview`
8. Run` Install-Module -Name Microsoft-Extractor-Suite`
9. Run `Import-Module .\Microsoft-Extractor-Suite.psd1`
10. Run `Connect-M365`
11. Get-UALAll

**Comment by gja3** [comment] 2024-11-18 05:25
Thanks for the response. Unfortunately, still no joy. I tried your steps since I hadn't touched the execution policy and am not sure whether I was running as Administrator before. FWIW, when I run all of the `Install-Module` commands, the prompt returns instantly with no output which says to me that each of those modules is already installed (the first time I ran them, it went through the whole sequence of loading and prompting me to confirm things).

**Comment by JoeyInvictus** [comment] 2024-11-18 07:55
@gja3, what @evild3ad is saying, do you have the View-Only Audit Logs assigned to the user? See:
https://learn.microsoft.com/en-us/purview/audit-search?tabs=microsoft-purview-portal

`You have to be assigned the Audit Logs or View-Only Audit Logs roles in the Microsoft Purview portal or Microsoft Purview compliance portal to search the audit log. By default, these roles are assigned to the Audit Manager and Audit Reader role groups on the Permissions page in the compliance portal. For more information, see [Get started with auditing solutions](https://learn.microsoft.com/en-us/purview/audit-get-started). To access audit cmdlets, you must be assigned the Audit Logs or View-Only Audit Logs roles in the Exchange admin center. You can also create custom role groups with the ability to search the audit log by adding the View-Only Audit Logs or Audit Logs roles to a custom role group.`

**Comment by JoeyInvictus** [comment] 2024-11-19 14:56
Hi @DfirJos, 

The Extractor Suite uses the `Search-UnifiedAuditLog` to collect the Unified Audit Log. This issue is not related to our tool, as the error message is connected to the underlying [PowerShell cmdlet](https://learn.microsoft.com/en-us/powershell/module/exchange/search-unifiedauditlog?view=exchange-ps).

**Check if Exchange Online Module is Installed**
First, you need to check if the Exchange Online module is installed on your machine.

`Get-Module -ListAvailable -Name ExchangeOnlineManagement`

If the module is not installed, you can install it using:

`Install-Module -Name ExchangeOnlineManagement -Scope CurrentUser -Force`

**Import the Exchange Online Module**
If the Exchange Online Management module is installed, you may need to import it into your current session:

`Import-Module ExchangeOnlineManagement`

**Connect to Exchange Online**
Once the module is imported, make sure to connect to Exchange Online using an account with the appropriate permissions to execute the `Search-UnifiedAuditLog` cmdlet. You can do this by using:

`Connect-ExchangeOnline`

**Check if Search-UnifiedAuditLog Cmdlet is Available**
You can verify if the `Search-UnifiedAuditLog` cmdlet is available by using the following command:

`Get-Command -Name Search-UnifiedAuditLog`

![image](https://github.com/user-attachments/assets/99caeec9-1994-4716-800f-43368759a9d0)

**Comment by gja3** [comment] 2024-11-20 03:56
Thank you @JoeyInvictus and @evild3ad, mine is working now after applying the appropriate permission in Exchange Admin Center. @DfirJos if you just added the permission, try opening a fresh PS/ExchangeOnline session. 

However, the tool is operating extremely slowly - I've been running `Get-UalAll` for the last 90 days on a relatively small organization and it is taking hours and hours to export just a few days' worth of logs. Is this expected?

**Comment by JoeyInvictus** [comment] 2024-11-20 07:02
@gja3, Unfortunately, this is a current limitation. Microsoft only supports retrieving a maximum of 5,000 records per API call, which means that if you need to acquire 1 million events in an environment, it requires around 200 API calls. Another constraint is that if the number of events in a given time interval exceeds 5,000, the API will only return those 5,000 records and ignore the rest. For example, if there are 7,000 events between 13:00 and 14:00, the API call will only return 5,000.

To handle this, our tool makes additional API calls to check if the event count is below 5,000 for a given interval. If it’s not, the interval is adjusted and retried, resulting in a higher number of API calls and potentially slowing down the process.

One potential workaround is to take advantage of Exchange Online’s limit of three concurrent remote PowerShell sessions per user. You can divide the acquisition period into three separate ranges and run `Get-UALAll` in three PowerShell windows simultaneously.

We always run `Get-UALAll` in the background while at the same time acquiring the UAL with filters for example filtering for the only one or two compromised users or focusing only on the dates around the incident.

I’m definitely open to suggestions for improving the performance. But currently unsure how. I did experiment with PowerShell's 7 `ForEach-Object -Parallel` feature, but I couldn’t get it to work as intended.

**Comment by JoeyInvictus** [comment] 2024-11-21 07:46
Will close this issue for now. Feel free to re-open or create a new one if there still issues/questions.

**Closed by JoeyInvictus** 2024-11-21 07:46 UTC
